export enum ActionType {
  SET_USER = 'SET_USER',
  SIGN_IN_API = 'SIGN_IN_API',
  TOGGLE_POST_MODAL = 'TOGGLE_POST_MODAL',
  SET_ARTICLE_LOADING = 'SET_ARTICLE_LOADING',
  GET_ARTICLES = 'GET_ARTICLES',
}
